name: levit_stress_tests
description: Pure Dart reactive state management primitives. The engine of the Levit framework.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter 
  levit_reactive:
    path: ../packages/levit_reactive
  levit_di:
    path: ../packages/levit_di
  levit_flutter:
    path: ../packages/levit_flutter
  levit_dart:
    path: ../packages/levit_dart
  test: ^1.24.0
  rxdart:

