name: flutter_dev_tool
description: "A new Flutter project."
version: 0.0.1
publish_to: 'none' 

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.8

  levit_monitor:
    path: ../../packages/core/levit_monitor
  levit_flutter_core:
    path: ../../packages/core/levit_flutter_core
  levit_dart_core:
    path: ../../packages/core/levit_dart_core
  dev_tool_server:
    path: ../dev_tool_server

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  freezed: ^3.2.4

flutter:
  uses-material-design: true
