name: levit_dart
description: The core framework for pure Dart applications. Aggregates dependency injection and reactivity.
repository: https://github.com/softilab/levit
version: 0.0.4

environment:
  sdk: ^3.0.0

dependencies:
  levit_di: ^0.0.4  
  levit_reactive: ^0.0.4
  meta: ^1.17.0

dev_dependencies:
  test: ^1.29.0
  rxdart: ^0.28.0
