name: levit_dart
description: Utility mixins and tools for Levit Dart controllers.
version: 0.0.6
repository: https://github.com/softilab/levit
topics:
  - utilities
  - mixins
  - tasks

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  levit_dart_core: ^0.0.6
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
