name: levit_flutter
description: Utility mixins and tools for Levit Flutter applications. Re-exports levit_dart_utility.
version: 0.0.6
repository: https://github.com/softilab/levit
topics:
  - flutter
  - utilities
  - widgets

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  levit_dart: ^0.0.6
  levit_flutter_core: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

