name: levit_scope
description: Pure Dart dependency injection and service locator. Part of the Levit framework.
repository: https://github.com/softilab/levit
version: 0.0.6
topics:
  - dependency-injection
  - service-locator
  - di

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
