name: levit_monitor
description: A monitoring package for Levit applications.
repository: https://github.com/softilab/levit
version: 0.0.4

environment:
  sdk: ^3.0.0

dependencies:
  # Levit Core
  levit_reactive: ^0.0.4
  levit_dart: ^0.0.4

  # Transports
  web_socket_channel: ^3.0.3
  
  # Annotations
  meta: ^1.18.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  rxdart: ^0.28.0
  stream_channel: ^2.1.4

