name: nexus_server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  levit_dart:
    path: ../../packages/levit_dart
  shared:
    path: ../shared
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
  async: ^2.11.0
  stream_channel: ^2.1.1
