name: levit_monitor
description: A monitoring package for Levit applications. Uses Scope and Reactive State middlewares to stream events to customizable transports.
repository: https://github.com/softilab/levit
version: 0.0.4

environment:
  sdk: ^3.0.0

dependencies:
  # Levit Core
  levit_reactive: ^0.0.5
  levit_dart_core: ^0.0.5  

  # Transports
  web_socket_channel: ^3.0.3
  
  # Annotations
  meta: ^1.17.0
  logger: ^2.6.2
  levit_scope: ^0.0.5

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
  rxdart: ^0.28.0
  stream_channel: ^2.1.4

