name: levit_reactive
description: Pure Dart reactive state management primitives. The engine of the Levit framework.
repository: https://github.com/softilab/levit
version: 0.0.4

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.29.0
  rxdart: ^0.28.0
  lints: ^6.0.0


